version: '3.8'

services:
  backend:
    container_name: music_backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    container_name: music_mongo
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: